apiVersion: serving.knative.dev/v1
kind: Service
metadata:
  name: harimau-backend
  annotations:
    run.googleapis.com/launch-stage: BETA
spec:
  template:
    metadata:
      annotations:
        autoscaling.knative.dev/minScale: "0"
        autoscaling.knative.dev/maxScale: "3"
    spec:
      containers:
      - image: gcr.io/GOOGLE_CLOUD_PROJECT/harimau-backend
        env:
        - name: GTI_MCP_MODE
          value: "http"
        # GTI_MCP_URL will be injected by Cloud Build deploy command
        - name: GTI_API_KEY
          valueFrom:
            secretKeyRef:
              name: GTI_API_KEY
              key: "latest"
        resources:
          limits:
            memory: 1Gi
            cpu: 1000m
        ports:
        - containerPort: 8080
