from typing import TypedDict, Annotated, List, Dict, Any, Optional
from langchain_core.messages import BaseMessage
import operator

def merge_dicts(a: Dict[str, Any], b: Dict[str, Any]) -> Dict[str, Any]:
    """Merges two dictionaries (shallow merge)."""
    return {**a, **b}

def last_value(a: Any, b: Any) -> Any:
    """Reducer that returns the last value (for scalar fields in parallel execution)."""
    return b if b is not None else a

def union_lists(a: Optional[List[str]], b: Optional[List[str]]) -> List[str]:
    """Union two lists without introducing duplicates."""
    res = list(a or [])
    for item in (b or []):
        if item not in res:
            res.append(item)
    return res

def merge_graphs(a: Optional[Any], b: Optional[Any]) -> Optional[Any]:
    """
    Merge two NetworkX graphs (for parallel specialist execution).
    When specialists run in parallel, both expand the graph independently.
    This ensures both sets of updates are preserved.
    """
    if a is None: return b
    if b is None: return a
    
    # Import here to avoid circular deps
    import networkx as nx
    
    # Deserialized graphs from dicts if necessary
    graph_a = nx.node_link_graph(a) if isinstance(a, dict) else a
    graph_b = nx.node_link_graph(b) if isinstance(b, dict) else b
    
    # Merge nodes
    combined = nx.MultiDiGraph(graph_a)
    for node, data in graph_b.nodes(data=True):
        if node in combined:
            # Node exists - deep merge attributes
            existing = combined.nodes[node]
            for key, val in data.items():
                if key not in existing:
                    existing[key] = val
                elif isinstance(val, dict) and isinstance(existing[key], dict):
                    existing[key].update(val)
                elif isinstance(val, list) and isinstance(existing[key], list):
                    res = list(existing[key])
                    for item in val:
                        if item not in res:
                            res.append(item)
                    existing[key] = res
                else:
                    existing[key] = val
        else:
            # New node - add it
            combined.add_node(node, **data)
    
    # Merge edges
    for u, v, data in graph_b.edges(data=True):
        rel = data.get("relationship")
        edge_matched = False
        if combined.has_edge(u, v):
            for edge_key, edge_data in combined[u][v].items():
                if edge_data.get("relationship") == rel:
                    edge_data.update(data)
                    edge_matched = True
                    break
        if not edge_matched:
            combined.add_edge(u, v, **data)
    
    # Return as dict for state persistence
    return nx.node_link_data(combined)

class AgentState(TypedDict):
    """
    State schema for the Harimau Investigation Graph.
    Passed between all nodes in the workflow.
    """
    job_id: Annotated[str, last_value]
    ioc: Annotated[str, last_value]
    ioc_type: Annotated[Optional[str], last_value]
    
    # Chat History: Stores the chain of thought and tool outputs
    messages: Annotated[List[BaseMessage], operator.add]
    
    # Subtasks: Tasks generated by Triage for Specialists
    # Example: [{"agent": "malware", "task": "Analyze behavior of hash..."}]
    subtasks: Annotated[List[Dict[str, Any]], last_value]
    
    # Outputs: Final results from specialists
    # Example: {"malware": {"verdict": "malicious", "details": "..."}}
    specialist_results: Annotated[Dict[str, Any], merge_dicts]
    
    # Final Report: The generated markdown report
    # Reverting to last_value since Lead Hunter now assembles report manually
    final_report: Annotated[Optional[str], last_value]
    
    # Metadata: Timing, errors, etc.
    metadata: Annotated[Dict[str, Any], merge_dicts]
    
    # Investigation Graph: NetworkX cache for full entity storage
    # Stores complete GTI attributes for all entities and relationships
    # CRITICAL: Uses merge_graphs to preserve updates from parallel specialists
    investigation_graph: Annotated[Optional[Any], merge_graphs]  # nx.MultiDiGraph (using Any to avoid import)
    
    # Iteration Control
    iteration: Annotated[int, last_value]  # Explicit iteration phase (0, 1, 2)

    # Investigation depth: controls cost vs. depth trade-off
    # Set from POST /api/investigate, persists unchanged through entire loop
    max_iterations: Annotated[int, last_value]
    
    lead_hunter_report: Annotated[Optional[str], last_value]  # Full synthesis report

    # Entities that have been assigned as subtasks across all iterations (for convergence detection)
    tasked_entities: Annotated[List[str], union_lists]