from typing import TypedDict, Annotated, List, Dict, Any, Optional
from langchain_core.messages import BaseMessage
import operator

def merge_dicts(a: Dict[str, Any], b: Dict[str, Any]) -> Dict[str, Any]:
    """Merges two dictionaries (shallow merge)."""
    return {**a, **b}

def last_value(a: Any, b: Any) -> Any:
    """Reducer that returns the last value (for scalar fields in parallel execution)."""
    return b if b is not None else a

class AgentState(TypedDict):
    """
    State schema for the Harimau Investigation Graph.
    Passed between all nodes in the workflow.
    """
    job_id: Annotated[str, last_value]
    ioc: Annotated[str, last_value]
    ioc_type: Annotated[Optional[str], last_value]
    
    # Chat History: Stores the chain of thought and tool outputs
    messages: Annotated[List[BaseMessage], operator.add]
    
    # Subtasks: Tasks generated by Triage for Specialists
    # Example: [{"agent": "malware", "task": "Analyze behavior of hash..."}]
    subtasks: Annotated[List[Dict[str, Any]], last_value]
    
    # Outputs: Final results from specialists
    # Example: {"malware": {"verdict": "malicious", "details": "..."}}
    specialist_results: Annotated[Dict[str, Any], merge_dicts]
    
    # Final Report: The generated markdown report
    final_report: Annotated[Optional[str], last_value]
    
    # Metadata: Timing, errors, etc.
    metadata: Annotated[Dict[str, Any], merge_dicts]
    
    # Investigation Graph: NetworkX cache for full entity storage
    # Stores complete GTI attributes for all entities and relationships
    investigation_graph: Annotated[Optional[Any], last_value]  # nx.MultiDiGraph (using Any to avoid import)
